# Generated by Django 6.0.1 on 2026-01-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_address_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.IntegerField(blank=True),
        ),
    ]
