# Generated by Django 6.0.1 on 2026-01-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentprofile_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
