# Generated by Django 6.0.1 on 2026-01-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studentprofile_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='experience_years',
            field=models.IntegerField(null=True),
        ),
    ]
