# Generated by Django 6.0.1 on 2026-01-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_alumniprofile_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='documentation_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, choices=[('web', 'Web Development'), ('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('iot', 'IoT'), ('blockchain', 'Blockchain'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_students',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Students'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, help_text='Example: Django, React, PostgreSQL', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
