# Generated by Django 6.0.1 on 2026-01-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_project_difficulty_level_project_documentation_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='interested_domains',
            field=models.JSONField(blank=True, default=list, help_text="Example: ['AI', 'Web', 'Cloud']"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_project_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_project_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_project_progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Progress percentage (0–100)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_project_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_project_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('paused', 'Paused'), ('completed', 'Completed')], default='ongoing', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_project_technologies',
            field=models.CharField(blank=True, help_text='Comma-separated technologies', max_length=300),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_project_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
